### ISSUE TITLE
User Story 12: Create Layout

### ISSUE THREAD

**Issue by ella-blaupause** [ella-blaupause/Capstone-EscapeRoom#25]

**Comment by ella-blaupause** [comment]
## Create Layout

## Value proposition

As an escape room player
I want the app to look good
so that I enjoy using it


## Description




![Image](https://user-images.githubusercontent.com/124199994/232768909-9013cb6e-6174-47ae-ba9d-5685a90b8d19.png)





## Acceptance criteria

- [ ] the style should be mobile first (iPhone SE)

## Tasks

- [ ] Create a Layout Component
- [ ] Implement styling


 
## Complexity

S

**Comment by rabe200** [comment]
lgtm - go for it!
